import json

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Analisis Keputusan Bantuan UMK Menggunakan Algoritma k-Nearest Neighbors (kNN)\n",
    "\n",
    "Notebook ini mendemonstrasikan bagaimana menerapkan algoritma **k-Nearest Neighbors (kNN)** untuk menentukan status keputusan kelayakan bantuan modal bagi tiga Usaha Mikro Kecil (UMK) baru berdasarkan data latih di `data/data.csv`.\n",
    "\n",
    "## 1. Konsep Perhitungan Jarak kNN\n",
    "\n",
    "Untuk mengukur kedekatan data baru dengan data latih, kita menggunakan rumus **Squared Euclidean Distance ($D^2$)**:\n",
    "$$D^2 = (x_1 - q_1)^2 + (x_2 - q_2)^2 + (x_3 - q_3)^2 + (x_4 - q_4)^2$$\n",
    "\n",
    "Di mana:\n",
    "- $q_1, q_2, q_3, q_4$ adalah nilai fitur dari data uji (query).\n",
    "- $x_1, x_2, x_3, x_4$ adalah nilai fitur dari data latih.\n",
    "\n",
    "### Fitur/Atribut yang Digunakan:\n",
    "- $X_1$ = Lama Usaha (tahun)\n",
    "- $X_2$ = Jumlah Pekerja\n",
    "- $X_3$ = Omzet (juta)\n",
    "- $X_4$ = Jumlah Aset\n",
    "- $Y$ = Kategori keputusan\n",
    "\n",
    "Pada simulasi ini, kita akan menampilkan detail perhitungan rumus jarak per baris data latih, diurutkan sesuai dengan urutan asli dataset, serta menyembunyikan kategori keputusan untuk baris yang bukan merupakan tetangga terdekat (dilambangkan dengan `-`), sesuai format lembar perhitungan tugas."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "from IPython.display import display, HTML\n",
    "\n",
    "# Set style sebaran\n",
    "sns.set_theme(style=\"whitegrid\")\n",
    "plt.rcParams[\"figure.figsize\"] = (12, 7)\n",
    "\n",
    "print(\"Library berhasil diimpor.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Load data latih\n",
    "train_df = pd.read_csv('data/data.csv')\n",
    "print(f\"Data Latih ({train_df.shape[0]} baris):\")\n",
    "display(train_df)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Definisikan data uji (query)\n",
    "test_data = [\n",
    "    {\"Nama_UKM\": \"Umk Pamurbaya\", \"Lama_Usaha\": 4, \"Jumlah_Pekerja\": 15, \"Omzet\": 4, \"Jumlah_Aset\": 6},\n",
    "    {\"Nama_UKM\": \"Umk Bandeng\", \"Lama_Usaha\": 3, \"Jumlah_Pekerja\": 28, \"Omzet\": 4, \"Jumlah_Aset\": 10},\n",
    "    {\"Nama_UKM\": \"Bukid Graffer\", \"Lama_Usaha\": 2, \"Jumlah_Pekerja\": 12, \"Omzet\": 1, \"Jumlah_Aset\": 3}\n",
    "]\n",
    "\n",
    "features = [\"Lama_Usaha\", \"Jumlah_Pekerja\", \"Omzet\", \"Jumlah_Aset\"]\n",
    "target_col = \"Hasil_Keputusan\"\n",
    "\n",
    "print(\"Data Uji:\")\n",
    "display(pd.DataFrame(test_data))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def run_knn_step_by_step(train_df, q, k=3):\n",
    "    q_val = np.array([q[f] for f in features])\n",
    "    df = train_df.copy()\n",
    "    \n",
    "    # Hitung Jarak Kuadrat\n",
    "    sq_dists = []\n",
    "    for _, row in df.iterrows():\n",
    "        x_val = row[features].values.astype(float)\n",
    "        sq_d = np.sum((x_val - q_val) ** 2)\n",
    "        sq_dists.append(sq_d)\n",
    "        \n",
    "    df['Square_Distance'] = sq_dists\n",
    "    df['Original_Index'] = df.index\n",
    "    \n",
    "    # Urutkan secara stabil untuk menentukan rank\n",
    "    sorted_df = df.sort_values(by=['Square_Distance', 'Original_Index']).reset_index(drop=True)\n",
    "    sorted_df['Jarak_Terkecil_Rank'] = sorted_df.index + 1\n",
    "    \n",
    "    # Kembalikan ke urutan asli data latih\n",
    "    df = sorted_df.sort_values(by='Original_Index').reset_index(drop=True)\n",
    "    \n",
    "    # Konstruksi visualisasi rumus\n",
    "    formulas = []\n",
    "    for _, row in df.iterrows():\n",
    "        parts = []\n",
    "        for f_name, q_v in zip(features, q_val):\n",
    "            parts.append(f\"({int(row[f_name])}-{int(q_v)})^2\")\n",
    "        expr = \" + \".join(parts)\n",
    "        formulas.append(f\"{expr} = {int(row['Square_Distance'])}\")\n",
    "        \n",
    "    df['Formula_Expr'] = formulas\n",
    "    return df, sorted_df"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Simulasi Lembar Perhitungan Jarak & Voting (k=3)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "k_val = 3\n",
    "\n",
    "for q in test_data:\n",
    "    q_name = q[\"Nama_UKM\"]\n",
    "    df_processed, df_sorted = run_knn_step_by_step(train_df, q, k_val)\n",
    "    \n",
    "    # Tampilkan Panel Profil\n",
    "    display(HTML(f\"\"\"\n",
    "    <div style='background: linear-gradient(135deg, #1e293b, #334155); color: #f8fafc; padding: 15px; border-radius: 12px; margin-top: 25px;'>\n",
    "        <h3 style='margin: 0; font-weight: 800; font-family: sans-serif; font-size: 1.25rem; letter-spacing: -0.025em;'>ANALISIS kNN: {q_name.upper()}</h3>\n",
    "        <p style='margin: 5px 0 0 0; opacity: 0.8; font-size: 0.95rem;'>\n",
    "            Data Query (q1, q2, q3, q4) = ({q['Lama_Usaha']}, {q['Jumlah_Pekerja']}, {q['Omzet']}, {q['Jumlah_Aset']})\n",
    "        </p>\n",
    "    </div>\n",
    "    \"\"\"))\n",
    "    \n",
    "    # Voting Mayoritas\n",
    "    nn_df = df_sorted.head(k_val)\n",
    "    votes = nn_df[target_col].value_counts().to_dict()\n",
    "    max_votes = max(votes.values())\n",
    "    candidates = [label for label, count in votes.items() if count == max_votes]\n",
    "    \n",
    "    if len(candidates) > 1:\n",
    "        # Ambil yang rank terkecil\n",
    "        resolved = None\n",
    "        for _, row_nn in nn_df.iterrows():\n",
    "            if row_nn[target_col] in candidates:\n",
    "                resolved = row_nn[target_col]\n",
    "                break\n",
    "        decision = resolved\n",
    "        note = \" (Resolusi Seri: Mengambil tetangga terdekat)\"\n",
    "    else:\n",
    "        decision = candidates[0]\n",
    "        note = \"\"\n",
    "        \n",
    "    color_map = {'YA': '#10b981', 'TIDAK': '#ef4444', 'TUNDA': '#f59e0b'}\n",
    "    color = color_map.get(decision, '#3b82f6')\n",
    "    \n",
    "    display(HTML(f\"\"\"\n",
    "    <div style='margin: 10px 0; font-size: 1.05rem;'>\n",
    "        <strong>Keputusan Akhir (k={k_val}):</strong> \n",
    "        <span style='color: {color}; font-weight: 800; padding: 3px 10px; background: {color}1a; border-radius: 6px;'>{decision}</span>\n",
    "        <span style='color: #64748b; font-size: 0.9em; margin-left: 10px;'>Voting Terbanyak: {votes}{note}</span>\n",
    "    </div>\n",
    "    \"\"\"))\n",
    "    \n",
    "    # Bangun Dataframe Tampilan Lembar Tugas\n",
    "    q_val_str = f\"{q['Lama_Usaha']},{q['Jumlah_Pekerja']},{q['Omzet']},{q['Jumlah_Aset']}\"\n",
    "    table_df = pd.DataFrame()\n",
    "    table_df['Nama UKM'] = df_processed['Nama_UKM']\n",
    "    table_df['X1 = Lama Usaha (tahun)'] = df_processed['Lama_Usaha']\n",
    "    table_df['X2 = Jumlah Pekerja'] = df_processed['Jumlah_Pekerja']\n",
    "    table_df['X3 = Omzet (juta)'] = df_processed['Omzet']\n",
    "    table_df['X4 = Jumlah Aset'] = df_processed['Jumlah_Aset']\n",
    "    table_df[f'Square distance to query distance ({q_val_str})'] = df_processed['Formula_Expr']\n",
    "    table_df['Jarak Terkecil'] = df_processed['Jarak_Terkecil_Rank']\n",
    "    table_df['Apakah termasuk nearest neighbor (K)'] = df_processed['Jarak_Terkecil_Rank'].apply(\n",
    "        lambda r: 'Ya' if r <= k_val else 'Tidak'\n",
    "    )\n",
    "    table_df['Y = kategori nearest neighbor'] = df_processed.apply(\n",
    "        lambda r: r[target_col] if r['Jarak_Terkecil_Rank'] <= k_val else '-', axis=1\n",
    "    )\n",
    "    \n",
    "    # Render tabel dengan gaya visual lembar tugas\n",
    "    display_html = (\n",
    "        table_df.style\n",
    "        .hide(axis='index')\n",
    "        .set_properties(**{'text-align': 'center', 'font-family': 'sans-serif', 'font-size': '12px'})\n",
    "        .set_properties(subset=['Nama UKM'], **{'text-align': 'left', 'font-weight': 'bold'})\n",
    "        .set_properties(subset=[f'Square distance to query distance ({q_val_str})'], **{'font-family': 'monospace', 'text-align': 'left', 'font-size': '11px', 'color': '#334155'})\n",
    "        .set_table_styles([\n",
    "            {'selector': 'th', 'props': [('background-color', '#475569'), ('color', 'white'), ('font-weight', 'bold'), ('text-align', 'center'), ('padding', '8px'), ('font-size', '12px')]},\n",
    "            {'selector': 'td', 'props': [('padding', '6px'), ('border-bottom', '1px solid #cbd5e1')]} \n",
    "        ])\n",
    "        .apply(lambda x: ['background-color: #dbeafe; font-weight: bold' if df_processed.loc[i, 'Jarak_Terkecil_Rank'] <= k_val else '' for i, _ in enumerate(x)], axis=0, subset=['Apakah termasuk nearest neighbor (K)'])\n",
    "        .apply(lambda x: ['background-color: #dbeafe; font-weight: bold; color: ' + color_map.get(df_processed.loc[i, target_col], '#000') if df_processed.loc[i, 'Jarak_Terkecil_Rank'] <= k_val else '' for i, _ in enumerate(x)], axis=0, subset=['Y = kategori nearest neighbor'])\n",
    "    )\n",
    "    display(display_html)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Visualisasi Grafik Distribusi Data UMK\n",
    "\n",
    "Mari kita gambarkan sebaran titik data latih berdasarkan atribut **Jumlah Pekerja** dan **Jumlah Aset**, serta posisi dari tiga titik data uji (query) baru."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "plt.figure(figsize=(13, 8))\n",
    "\n",
    "# Sebaran data latih berdasarkan keputusan\n",
    "colors = {'YA': '#10b981', 'TIDAK': '#ef4444', 'TUNDA': '#f59e0b'}\n",
    "for label, group in train_df.groupby('Hasil_Keputusan'):\n",
    "    plt.scatter(\n",
    "        group['Jumlah_Pekerja'], \n",
    "        group['Jumlah_Aset'], \n",
    "        label=f\"Latih: {label}\",\n",
    "        color=colors[label],\n",
    "        s=120, \n",
    "        alpha=0.8, \n",
    "        edgecolors='black',\n",
    "        linewidths=1.2\n",
    "    )\n",
    "    for _, row in group.iterrows():\n",
    "        plt.annotate(\n",
    "            row['Nama_UKM'], \n",
    "            (row['Jumlah_Pekerja'], row['Jumlah_Aset']),\n",
    "            textcoords=\"offset points\", \n",
    "            xytext=(0,8), \n",
    "            ha='center',\n",
    "            fontsize=8,\n",
    "            alpha=0.75,\n",
    "            weight='bold'\n",
    "        )\n",
    "\n",
    "# Sebaran data uji\n",
    "markers = ['D', 's', '^']\n",
    "for i, q in enumerate(test_data):\n",
    "    plt.scatter(\n",
    "        q['Jumlah_Pekerja'], \n",
    "        q['Jumlah_Aset'], \n",
    "        label=f\"Uji: {q['Nama_UKM']}\", \n",
    "        color='blue', \n",
    "        marker=markers[i], \n",
    "        s=180, \n",
    "        edgecolors='white', \n",
    "        linewidths=2.0,\n",
    "        zorder=5\n",
    "    )\n",
    "    plt.annotate(\n",
    "        f\"* {q['Nama_UKM'].upper()}\", \n",
    "        (q['Jumlah_Pekerja'], q['Jumlah_Aset']),\n",
    "        textcoords=\"offset points\", \n",
    "        xytext=(0,-18), \n",
    "        ha='center',\n",
    "        color='blue',\n",
    "        fontsize=9,\n",
    "        weight='bold',\n",
    "        zorder=6\n",
    "    )\n",
    "\n",
    "plt.title('Diagram Pencar Sebaran UMK: Jumlah Pekerja vs Jumlah Aset', fontsize=15, fontweight='bold', pad=15)\n",
    "plt.xlabel('Jumlah Pekerja (Orang)', fontsize=11, fontweight='bold')\n",
    "plt.ylabel('Jumlah Aset', fontsize=11, fontweight='bold')\n",
    "plt.legend(frameon=True, facecolor='white', framealpha=0.9, fontsize=10, loc='best')\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}

with open('main.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=1)

print("Jupyter notebook main.ipynb generated successfully.")
